version: "3.8"
services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
      target: development
    develop:
      watch:
        - path: ./api/package.json
          action: rebuild
        - path: ./api
          target: /app
          action: sync
    ports:
      - 8080:8080
    depends_on:
      - database
    env_file: ./api/.env 
    networks:
      - dev

  database:
    image: mongo:latest
    restart: always
    volumes:
      - database-data:/data/db
    ports:
      - 27017:27017
    networks:
      - dev

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - '3000:3000'
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend
          target: /app/
          action: sync
    networks:
      - dev

  # minio:
  #   image: minio/minio:latest
  #   ports:
  #     - "9000:9000"
  #     - "8900:8900"
  #   volumes:
  #     - minio:/data/minio
  #   environment:
  #     MINIO_ROOT_USER: admin
  #     MINIO_ROOT_PASSWORD: adminadmin
  #   command: 'minio server data/minio --console-address ":8900"'    
  #   networks:
  #     - dev
    
volumes:
  database-data:
  # minio:

networks:
 dev: