version: "3.9"

services:
  frontend:
    image: node:lts-alpine
    restart: "no"
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    command:
      - sh
      - -c
      - |
          yarn install
          yarn run dev
    ports:
      - 3000:3000

  api:
    image: node:lts-alpine
    restart: "no"
    volumes:
      - ./api:/api
    working_dir: /api
    command:
      - sh
      - -c
      - |
        npm run start:dev
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      MONGO_URL: mongodb://localhost:27017/samybase
    networks:
      - dev

  database:
    image: mongo:latest
    restart: always
    volumes:
      - database-data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    networks:
      - dev
      
volumes:
  database-data:

networks:
  dev: