
import Header from '@/components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import Providers from "@/utils/provider";
import AuthProviders from "@/utils/provider";
import { ReduxProviders } from '@/redux/provider';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <body className={inter.className}>
          <Providers>
            <ReduxProviders>
              <AuthProviders>
                <Header/>
                {children}
              </AuthProviders>
            </ReduxProviders>
          </Providers>
        </body>
      </html>
  )
}
